### ISSUE TITLE
Running demos in Ubuntu 20.04

### ISSUE THREAD

**Issue by Zhamemo** [ezod/adolphus#37]
It's running in ubuntu 20.04 with a conda virtual environment, in which `python=3.6.13, pyyaml=6.0, cython=0.29.32, pycollada=0.7.2, setuptools=58.0.4, vpython=7.6.2, pycairo=1.20.1, pygobject=3.42.2, epydoc=3.0.1.`
However, while the demos of collada, follow and laserplan are running,  error occurs in  that time. Here is the error:
```
Traceback (most recent call last):
  File "/home/zmm/PycharmProjects/adolphus/demos/collada/collada_test.py", line 1, in <module>
    from adolphus.interface import Experiment
  File "/home/zmm/PycharmProjects/adolphus/adolphus/interface.py", line 15, in <module>
    from .geometry import Point, Rotation, Pose
  File "adolphus/geometry.pyx", line 780, in init adolphus.geometry
  File "adolphus/geometry.pyx", line 552, in adolphus.geometry.Rotation.__init__
  File "adolphus/geometry.pyx", line 490, in adolphus.geometry.Quaternion.unit
  File "adolphus/geometry.pyx", line 500, in adolphus.geometry.Quaternion.unit
TypeError: unsupported operand type(s) for /: 'adolphus.geometry.Quaternion' and 'float'
```

**Comment by wenjinshi** [comment]
Hello，I encountered the same problem as you. I want to ask if your problem has been solved, or if there are other reference materials for learning?
